### ISSUE TITLE
[Bug]: `chains` and `assetsLists` configuration mismatch causes a runtime error when using `connect`

### ISSUE THREAD

**Issue by Juzorensen** [nabla-studio/quirks#82]
### Prerequisites

- [X] You read the guidelines for contributing.
- [X] You are able to reproduce the problem in the latest version of Quirks.
- [X] You checked that the problem has not yet been reported (also through closed issues).

### Describe the exact steps to reproduce the problem in as many details as possible

Using nextjs with those dependencies:

- `@nabla-studio/chain-registry`
- `@quirks/react`
- `@quirks/store`
- `@quirks/wallets`

When passing the following configuration to `QuirksConfig`:

```
const CONFIG: Config = {
  assetsLists: [osmosisAssetList, kavaAssetList], // Note the missing akash asset list.
  autoConnect: true,
  chains: [akash, osmosis, kava],
  wallets: [keplrExtension, leapExtension],
};
```

### Describe the issue behavior

When using the `connect` methods of the `useConnect` hook, it produces the following runtime error:

![Screenshot 2024-03-05 at 2 29 37 PM](https://github.com/nabla-studio/quirks/assets/85519918/32662c0a-9de5-45e1-a0c0-0915654db4f3)

**Comment by DavideSegullo** [comment]
Hola @Juzorensen, thank you for opening this issue!

What is the specific case you want to implement? In what case do you need to not have the list of assets associated with a chain?

You can get rid of this problem by disabling `autoSuggestions` parameter from quirks config:
https://quirks.nabla.studio/docs/config#types

It should not give you any side effect but if the chain you are using is not available in the wallet you want to use, then you will get error from the wallet because it will tell you that chain X does not exist.

Let me know if this can be a viable solution for you or if you need more support!

**Comment by Juzorensen** [comment]
After thinking about it I understand the current implementation.

Maybe the error is just confusing to an outsider like me. I don't have any good suggestions to improve this. I'll close the issues.

Thanks for your support ❤️

**Comment by DavideSegullo** [comment]
> After thinking about it I understand the current implementation.
> 
> Maybe the error is just confusing to an outsider like me. I don't have any good suggestions to improve this. I'll close the issue.
> 
> Thanks for your support ❤️

I'll improve the error message! Thank you for your feedback
